name: Run amz_mail.py

on:
  schedule:
    - cron: "0 22 * * *"  # 10 PM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Selenium and Required Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Step 4: Run the Python Script
      - name: Run amz_mail.py
        run: python amz_mail.py
