name: Run amz_mail.py

on:
  schedule:
    - cron: "0 10 * * *"  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Required Libraries (including webdriver-manager)
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Step 4: Modify amz_mail.py to use webdriver-manager
      - name: Update ChromeDriver with webdriver-manager
        run: |
          sed -i "s|webdriver.Chrome(options=options)|webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)|" amz_mail.py

      # Step 5: Run the Python script with environment variables
      - name: Run amz_mail.py
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python amz_mail.py
