name: Run amz_mail.py

on:
  schedule:
    - cron: "0 10 * * *"  # Runs daily at 10 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      # Step 3: Install Python dependencies
      - name: Install Required Libraries
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Step 4: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q "https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver.zip

      # Step 5: Run the Python script
      - name: Run amz_mail.py
        run: python amz_mail.py
