name: Run amz_mail.py

# Schedule the workflow to run at 10 PM UTC daily
on:
  schedule:
    - cron: "0 22 * * *"  # 10 PM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository content
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify Python version

      # Step 3: Install Python packages
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip

      # Step 4: Install Selenium and ChromeDriver
      - name: Install Selenium and ChromeDriver
        run: |
          chmod +x install_chr_sel_ium.sh
          ./install_chr_sel_ium.sh

      # Step 5: Run the Python script
      - name: Run amz_mail.py
        run: python amz_mail.py
